m=int(input('Uma distância em metros: '))
km = (m/1000)
hm = (m/100)
dam = (m/10)
dm = (m/1)
c = (m*100)
mi = (m*1000)
print('A medida de {}.0m corresponde a \n{}km\n{}hm\n{}dam\n{}dm\n{}cm\n{}mm'.format(m, km, hm, dam, dam, c, mi))