n = input('Digite o seu nome completo: ')
Ma = n.upper()
Mi = n.lower()
Se = len(n.replace(' ', ''))
Pn = n.split()
print('Olá {}, seja bem vindo!'.format(n))
print('Este é seu nome convertido para letras maiúsculas: {}'.format(Ma))
print('Este é seu nome convertido para letras minúsculas: {}'.format(Mi))
print('Seu nome é composto por {} letras!'.format(Se))
print('E seu primeiro nome é composto por {} letras!'.format(len(Pn[0])))
